/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
        roboto: ["Roboto", "sans-serif"],
        montserrat: ["Montserrat", "sans-serif"],
        lora: ["Lora", "serif"],
        fancy: ["Dancing Script", "cursive"],
        inter: ["Inter", "sans-serif"],
        anton: ["Anton", "sans-serif"],
        pacifico: ["Pacifico", "cursive"],
        orbitron: ["Orbitron", "sans-serif"],
        raleway: ["Raleway", "sans-serif"],
        ubuntu: ["Ubuntu", "sans-serif"],
        merriweather: ["Merriweather", "serif"],
        openSans: ["Open Sans", "sans-serif"],
        nunito: ["Nunito", "sans-serif"],
        quicksand: ["Quicksand", "sans-serif"],
        bebas: ["Bebas Neue", "sans-serif"],
        playfair: ["Playfair Display", "serif"],
        manrope: ["Manrope", "sans-serif"],
        exo: ["Exo", "sans-serif"],
        rubik: ["Rubik", "sans-serif"],
        barlow: ["Barlow", "sans-serif"],
        josefin: ["Josefin Sans", "sans-serif"],
        lato: ["Lato", "sans-serif"],
        titillium: ["Titillium Web", "sans-serif"],
        ptserif: ["PT Serif", "serif"],
        oswald: ["Oswald", "sans-serif"],
        amatic: ["Amatic SC", "cursive"],
        fira: ["Fira Sans", "sans-serif"],
        zilla: ["Zilla Slab", "serif"],
        source: ["Source Sans Pro", "sans-serif"],
        cabin: ["Cabin", "sans-serif"],
        varela: ["Varela Round", "sans-serif"],
        crete: ["Crete Round", "serif"],
        cardo: ["Cardo", "serif"],
        tangerine: ["Tangerine", "cursive"],
        baloo: ["Baloo 2", "sans-serif"],
        indie: ["Indie Flower", "cursive"],
        caveat: ["Caveat", "cursive"],
        kaushan: ["Kaushan Script", "cursive"],
        architects: ["Architects Daughter", "cursive"],
        shadows: ["Shadows Into Light", "cursive"],
        courgette: ["Courgette", "cursive"],
        patua: ["Patua One", "cursive"],
        pressstart: ["Press Start 2P", "cursive"],
        metal: ["Metal Mania", "cursive"],
        lemonada: ["Lemonada", "cursive"],
        yatra: ["Yatra One", "cursive"],
        aladin: ["Aladin", "cursive"],
      },
    },
  },
  plugins: [],
};
